// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS5V3egsXy5kQA9Y9ob_Eq9nOiikn7JJU',
    appId: '1:932572359552:web:9875443544aba2ba28af65',
    messagingSenderId: '932572359552',
    projectId: 'food-buds-back-end-201',
    authDomain: 'food-buds-back-end-201.firebaseapp.com',
    storageBucket: 'food-buds-back-end-201.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4uRHeg5sDumAQgHE3pKQ6o6FndgFDsPU',
    appId: '1:932572359552:android:1df442fc77bd820c28af65',
    messagingSenderId: '932572359552',
    projectId: 'food-buds-back-end-201',
    storageBucket: 'food-buds-back-end-201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8rUOAwPmclLB3u6Z4Mia7oIIxrDhqKa4',
    appId: '1:932572359552:ios:a4a2d3715eea9b3928af65',
    messagingSenderId: '932572359552',
    projectId: 'food-buds-back-end-201',
    storageBucket: 'food-buds-back-end-201.appspot.com',
    iosBundleId: 'com.example.foodbuds01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8rUOAwPmclLB3u6Z4Mia7oIIxrDhqKa4',
    appId: '1:932572359552:ios:a4a2d3715eea9b3928af65',
    messagingSenderId: '932572359552',
    projectId: 'food-buds-back-end-201',
    storageBucket: 'food-buds-back-end-201.appspot.com',
    iosBundleId: 'com.example.foodbuds01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS5V3egsXy5kQA9Y9ob_Eq9nOiikn7JJU',
    appId: '1:932572359552:web:b0d64c4e3157491d28af65',
    messagingSenderId: '932572359552',
    projectId: 'food-buds-back-end-201',
    authDomain: 'food-buds-back-end-201.firebaseapp.com',
    storageBucket: 'food-buds-back-end-201.appspot.com',
  );
}
