import 'package:foodbuds0_1/models/models.dart';

class RestaurantRepository {
  final List<Restaurant> restaurants = [
    const Restaurant(
      id: '1',
      restaurantName: 'Lezzet Durağı',
      location: 'İzmir',
      cuisineType: 'Turkish',
      rating: '4.5',
      filePath: 'images/lezzet_duragi.jpg',
      closingHour: '23:00',
    ),
    const Restaurant(
      id: '2',
      restaurantName: 'Pasta e Basta',
      location: 'İstanbul',
      cuisineType: 'Italian',
      rating: '4.7',
      filePath: 'images/pasta_e_basta.jpg',
      closingHour: '22:00',
    ),
    const Restaurant(
      id: '3',
      restaurantName: 'Bistro de Paris',
      location: 'İzmir',
      cuisineType: 'French',
      rating: '4.6',
      filePath: 'images/bistro_de_paris.jpg',
      closingHour: '23:30',
    ),
    const Restaurant(
      id: '4',
      restaurantName: 'Dragon Wok',
      location: 'İstanbul',
      cuisineType: 'Chinese',
      rating: '4.4',
      filePath: 'images/dragon_wok.jpg',
      closingHour: '22:30',
    ),
    const Restaurant(
      id: '5',
      restaurantName: 'Sushi World',
      location: 'İzmir',
      cuisineType: 'Japanese',
      rating: '4.8',
      filePath: 'images/sushi_world.jpg',
      closingHour: '23:00',
    ),
    const Restaurant(
      id: '6',
      restaurantName: 'Curry House',
      location: 'İstanbul',
      cuisineType: 'Indian',
      rating: '4.3',
      filePath: 'images/curry_house.jpg',
      closingHour: '22:00',
    ),
    const Restaurant(
      id: '7',
      restaurantName: 'El Ranchero',
      location: 'İzmir',
      cuisineType: 'Mexican',
      rating: '4.5',
      filePath: 'images/el_ranchero.jpg',
      closingHour: '23:30',
    ),
    const Restaurant(
      id: '8',
      restaurantName: 'Tapas Bar',
      location: 'İstanbul',
      cuisineType: 'Spanish',
      rating: '4.6',
      filePath: 'images/tapas_bar.jpg',
      closingHour: '22:30',
    ),
    const Restaurant(
      id: '9',
      restaurantName: 'Thai Garden',
      location: 'İzmir',
      cuisineType: 'Thai',
      rating: '4.7',
      filePath: 'images/thai_garden.jpg',
      closingHour: '23:00',
    ),
    const Restaurant(
      id: '10',
      restaurantName: 'Burger Joint',
      location: 'İstanbul',
      cuisineType: 'American',
      rating: '4.4',
      filePath: 'images/burger_joint.jpg',
      closingHour: '22:00',
    ),
    const Restaurant(
      id: '11',
      restaurantName: 'Kebapçı Ahmet',
      location: 'İzmir',
      cuisineType: 'Turkish',
      rating: '4.5',
      filePath: 'images/kebapci_ahmet.jpg',
      closingHour: '23:00',
    ),
    const Restaurant(
      id: '12',
      restaurantName: 'La Trattoria',
      location: 'İstanbul',
      cuisineType: 'Italian',
      rating: '4.6',
      filePath: 'images/la_trattoria.jpg',
      closingHour: '22:00',
    ),
    const Restaurant(
      id: '13',
      restaurantName: 'Le Petit Bistro',
      location: 'İzmir',
      cuisineType: 'French',
      rating: '4.7',
      filePath: 'images/le_petit_bistro.jpg',
      closingHour: '23:30',
    ),
    const Restaurant(
      id: '14',
      restaurantName: 'Peking Express',
      location: 'İstanbul',
      cuisineType: 'Chinese',
      rating: '4.4',
      filePath: 'images/peking_express.jpg',
      closingHour: '22:30',
    ),
    const Restaurant(
      id: '15',
      restaurantName: 'Sakura Sushi',
      location: 'İzmir',
      cuisineType: 'Japanese',
      rating: '4.8',
      filePath: 'images/sakura_sushi.jpg',
      closingHour: '23:00',
    ),
    const Restaurant(
      id: '16',
      restaurantName: 'Spice Route',
      location: 'İstanbul',
      cuisineType: 'Indian',
      rating: '4.3',
      filePath: 'images/spice_route.jpg',
      closingHour: '22:00',
    ),
    const Restaurant(
      id: '17',
      restaurantName: 'Cantina Mexicana',
      location: 'İzmir',
      cuisineType: 'Mexican',
      rating: '4.5',
      filePath: 'images/cantina_mexicana.jpg',
      closingHour: '23:30',
    ),
    const Restaurant(
      id: '18',
      restaurantName: 'Casa de Tapas',
      location: 'İstanbul',
      cuisineType: 'Spanish',
      rating: '4.6',
      filePath: 'images/casa_de_tapas.jpg',
      closingHour: '22:30',
    ),
    const Restaurant(
      id: '19',
      restaurantName: 'Bangkok Bites',
      location: 'İzmir',
      cuisineType: 'Thai',
      rating: '4.7',
      filePath: 'images/bangkok_bites.jpg',
      closingHour: '23:00',
    ),
    const Restaurant(
      id: '20',
      restaurantName: 'Big Apple Diner',
      location: 'İstanbul',
      cuisineType: 'American',
      rating: '4.4',
      filePath: 'images/big_apple_diner.jpg',
      closingHour: '22:00',
    ),
  ];

  List<Restaurant> getRestaurants() {
    return restaurants;
  }
}
